In [240]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append("../rgbd-reg")

import torch
import numpy as np

from vkitti import vkitti

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [277]:
dset = vkitti("/home/ios/data/", True, download=True)
dl = torch.utils.data.DataLoader(dset, shuffle=True)

extracting tar ...
extracting tar ...
loading images...
loading images...
loading params...
loading params...


In [278]:
x = dl.dataset[0]#next(iter(dl))
x

(tensor([[[ 0.9277,  0.9277,  0.9277,  ..., -0.8209, -0.7673, -0.5849],
          [ 0.9277,  0.9277,  0.9277,  ..., -0.8424, -0.7780, -0.6493],
          [ 0.9385,  0.9385,  0.9385,  ..., -0.8424, -0.8209, -0.7673],
          ...,
          [ 1.2818,  1.2818,  1.2818,  ..., -1.1964, -1.1964, -1.1964],
          [ 1.2710,  1.2710,  1.2818,  ..., -1.1964, -1.1964, -1.1964],
          [ 1.2710,  1.2710,  1.2818,  ..., -1.1964, -1.1964, -1.1964]]]),
 tensor([[[65535., 65535., 65535.,  ...,   995.,   993.,   990.],
          [65535., 65535., 65535.,  ...,   995.,   993.,   991.],
          [65535., 65535., 65535.,  ...,   995.,   993.,   991.],
          ...,
          [  808.,   809.,   810.,  ...,   355.,   354.,   354.],
          [  808.,   809.,   810.,  ...,   355.,   354.,   354.],
          [  808.,   808.,   809.,  ...,   355.,   354.,   354.]]]),
 array([  0.    ,   0.    , 725.0087, 725.0087, 620.5   , 187.    ]),
 array([ 0.000000e+00,  0.000000e+00, -8.019686e-03,  7.217909e-02

In [279]:
gray = x[0][0].squeeze()
d = x[1][0].squeeze()
d

tensor([[65535., 65535., 65535.,  ...,   995.,   993.,   990.],
        [65535., 65535., 65535.,  ...,   995.,   993.,   991.],
        [65535., 65535., 65535.,  ...,   995.,   993.,   991.],
        ...,
        [  808.,   809.,   810.,  ...,   355.,   354.,   354.],
        [  808.,   809.,   810.,  ...,   355.,   354.,   354.],
        [  808.,   808.,   809.,  ...,   355.,   354.,   354.]])

In [280]:
intr = x[2][2:]
intr

array([725.0087, 725.0087, 620.5   , 187.    ])

In [281]:
intr = np.insert(intr, (1, 2), (0))
intr = np.append(intr, (0, 0, 1))
intr = intr.reshape(3, 3)
intr = np.hstack((intr, [[0], [0], [0]]))
intr = np.vstack((intr, [0, 0, 0, 1]))
intr

array([[725.0087,   0.    , 725.0087,   0.    ],
       [  0.    , 620.5   , 187.    ,   0.    ],
       [  0.    ,   0.    ,   1.    ,   0.    ],
       [  0.    ,   0.    ,   0.    ,   1.    ]])

In [282]:
point = d[10, 10] * np.linalg.inv(intr) @ np.array((10, 10, 1, 1/d[10, 10]))

In [283]:
point

tensor([-6.4631e+04, -1.8694e+04,  6.5535e+04,  1.0000e+00],
       dtype=torch.float64)

In [284]:
extr = x[3][2:]
extr = extr.reshape(4, 4)
extr

array([[-8.019686e-03,  7.217909e-02, -9.973595e-01,  7.494453e+00],
       [-9.896867e-04,  9.973904e-01,  7.218930e-02,  1.124036e+02],
       [ 9.999674e-01,  1.566000e-03, -7.927299e-03, -7.717823e-01],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [285]:
pix = 1/point[2] * intr @ point

In [286]:
pix /= 1/point[3]

In [287]:
pix

tensor([1.0000e+01, 1.0000e+01, 1.0000e+00, 1.5259e-05], dtype=torch.float64)

In [267]:
x = dl.dataset[1]#next(iter(dl))
x

(tensor([[[ 0.9350,  0.9350,  0.9350,  ..., -0.5285, -0.5931, -0.5285],
          [ 0.9350,  0.9350,  0.9350,  ..., -0.4101, -0.6146, -0.6038],
          [ 0.9350,  0.9350,  0.9350,  ..., -0.5500, -0.6146, -0.5715],
          ...,
          [ 1.3009,  1.3009,  1.3009,  ..., -1.2172, -1.2279, -1.1096],
          [ 1.3116,  1.3116,  1.3116,  ..., -1.1957, -1.2172, -1.1741],
          [ 1.3224,  1.3224,  1.3224,  ..., -1.1849, -1.1957, -1.2172]]]),
 tensor([[[ 2.0187,  2.0187,  2.0187,  ..., -0.5281, -0.5282, -0.5282],
          [ 2.0187,  2.0187,  2.0187,  ..., -0.5280, -0.5282, -0.5282],
          [ 2.0187,  2.0187,  2.0187,  ..., -0.5280, -0.5282, -0.5282],
          ...,
          [-0.5356, -0.5356, -0.5355,  ..., -0.5538, -0.5538, -0.5538],
          [-0.5356, -0.5356, -0.5355,  ..., -0.5537, -0.5537, -0.5537],
          [-0.5356, -0.5356, -0.5355,  ..., -0.5537, -0.5537, -0.5537]]]),
 array([  0.    ,   1.    , 725.0087, 725.0087, 620.5   , 187.    ]),
 array([ 0.000000e+00,  1.0000

In [268]:
extr = x[3][2:]
extr = extr.reshape(4, 4)
extr

array([[-8.019686e-03,  7.217909e-02, -9.973595e-01,  6.961728e+00],
       [-9.896867e-04,  9.973904e-01,  7.218930e-02,  1.124036e+02],
       [ 9.999674e-01,  1.566000e-03, -7.927299e-03, -7.717823e-01],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [269]:
x = dl.dataset[2]#next(iter(dl))
x

(tensor([[[ 0.9634,  0.9634,  0.9634,  ..., -0.6102, -0.5779, -0.5347],
          [ 0.9634,  0.9634,  0.9634,  ..., -0.6856, -0.5994, -0.5455],
          [ 0.9634,  0.9634,  0.9634,  ..., -0.6641, -0.5455, -0.4916],
          ...,
          [ 1.2652,  1.2652,  1.2652,  ..., -1.0844, -1.0844, -1.0844],
          [ 1.2760,  1.2760,  1.2760,  ..., -1.0952, -1.0844, -1.0844],
          [ 1.2868,  1.2976,  1.2976,  ..., -1.0952, -1.0844, -1.0844]]]),
 tensor([[[ 2.0461,  2.0461,  2.0461,  ..., -0.5220, -0.5221, -0.5222],
          [ 2.0461,  2.0461,  2.0461,  ..., -0.5220, -0.5221, -0.5222],
          [ 2.0461,  2.0461,  2.0461,  ..., -0.5220, -0.5221, -0.5222],
          ...,
          [-0.5298, -0.5298, -0.5298,  ..., -0.5488, -0.5489, -0.5489],
          [-0.5298, -0.5298, -0.5298,  ..., -0.5488, -0.5489, -0.5489],
          [-0.5298, -0.5298, -0.5298,  ..., -0.5488, -0.5489, -0.5489]]]),
 array([  1.    ,   0.    , 725.0087, 725.0087, 620.5   , 187.    ]),
 array([ 1.000000e+00,  0.0000

In [270]:
extr = x[3][2:]
extr = extr.reshape(4, 4)
extr

array([[-7.779241e-03,  7.307380e-02, -9.972962e-01,  7.283874e+00],
       [ 6.943159e-04,  9.973266e-01,  7.307061e-02,  1.124180e+02],
       [ 9.999694e-01, -1.240000e-04, -7.809162e-03, -2.094175e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [271]:
x = dl.dataset[4]#next(iter(dl))
x

(tensor([[[ 1.0267,  1.0267,  1.0267,  ..., -0.5449, -0.3390, -0.5016],
          [ 1.0267,  1.0267,  1.0267,  ..., -0.4907, -0.3823, -0.4474],
          [ 1.0267,  1.0267,  1.0267,  ..., -0.5341, -0.3823, -0.3606],
          ...,
          [ 1.2977,  1.1893,  1.1351,  ..., -1.1519, -1.1519, -1.1519],
          [ 0.6365,  0.6907,  0.4306,  ..., -1.1410, -1.1519, -1.1519],
          [ 0.1704,  0.3981,  0.4631,  ..., -1.1410, -1.1519, -1.1519]]]),
 tensor([[[ 2.0950,  2.0950,  2.0950,  ..., -0.5116, -0.5117, -0.5118],
          [ 2.0950,  2.0950,  2.0950,  ..., -0.5116, -0.5117, -0.5118],
          [ 2.0950,  2.0950,  2.0950,  ..., -0.5116, -0.5117, -0.5118],
          ...,
          [-0.5199, -0.5199, -0.5199,  ..., -0.5395, -0.5396, -0.5396],
          [-0.5200, -0.5201, -0.5201,  ..., -0.5395, -0.5396, -0.5396],
          [-0.5203, -0.5203, -0.5203,  ..., -0.5395, -0.5396, -0.5396]]]),
 array([  2.    ,   0.    , 725.0087, 725.0087, 620.5   , 187.    ]),
 array([ 2.000000e+00,  0.0000

In [272]:
extr = x[3][2:]
extr = extr.reshape(4, 4)
extr

array([[-8.015394e-03,  6.971319e-02, -9.975349e-01,  6.626684e+00],
       [-1.972947e-03,  9.975639e-01,  6.973107e-02,  1.124692e+02],
       [ 9.999660e-01,  2.527006e-03, -7.858276e-03, -2.832348e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [273]:
x = dl.dataset[6]#next(iter(dl))
x

(tensor([[[ 1.0943,  1.0943,  1.0943,  ...,  1.2611,  1.2611,  1.2611],
          [ 1.0943,  1.0943,  1.0943,  ...,  1.2611,  1.2611,  1.2611],
          [ 1.0943,  1.0943,  1.0943,  ...,  1.2611,  1.2611,  1.2611],
          ...,
          [ 1.3946,  1.3946,  1.4503,  ..., -1.1976, -1.1865, -1.1865],
          [ 1.4836,  1.3946,  1.3946,  ..., -1.1865, -1.1754, -1.1754],
          [ 1.0052,  0.7160,  0.5602,  ..., -1.1865, -1.1865, -1.1865]]]),
 tensor([[[ 2.0965,  2.0965,  2.0965,  ...,  2.0965,  2.0965,  2.0965],
          [ 2.0965,  2.0965,  2.0965,  ...,  2.0965,  2.0965,  2.0965],
          [ 2.0965,  2.0965,  2.0965,  ...,  2.0965,  2.0965,  2.0965],
          ...,
          [-0.5218, -0.5218, -0.5217,  ..., -0.5381, -0.5381, -0.5381],
          [-0.5218, -0.5218, -0.5217,  ..., -0.5380, -0.5381, -0.5381],
          [-0.5218, -0.5218, -0.5218,  ..., -0.5380, -0.5381, -0.5381]]]),
 array([  3.    ,   0.    , 725.0087, 725.0087, 620.5   , 187.    ]),
 array([ 3.000000e+00,  0.0000

In [274]:
extr = x[3][2:]
extr = extr.reshape(4, 4)
extr

array([[-8.151174e-03,  6.922305e-02, -9.975680e-01,  6.289214e+00],
       [-6.129198e-03,  9.975789e-01,  6.927389e-02,  1.125098e+02],
       [ 9.999481e-01,  6.678950e-03, -7.707238e-03, -3.399123e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])